// flow-typed signature: 0329b59190a39e5e828d1075bf08cd83
// flow-typed version: <<STUB>>/react-virtuoso_v^0.20.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-virtuoso'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-virtuoso' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-virtuoso/dist' {
  declare module.exports: any;
}

declare module 'react-virtuoso/dist/react-virtuoso.cjs.development' {
  declare module.exports: any;
}

declare module 'react-virtuoso/dist/react-virtuoso.cjs.production.min' {
  declare module.exports: any;
}

declare module 'react-virtuoso/dist/react-virtuoso.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-virtuoso/dist/index' {
  declare module.exports: $Exports<'react-virtuoso/dist'>;
}
declare module 'react-virtuoso/dist/index.js' {
  declare module.exports: $Exports<'react-virtuoso/dist'>;
}
declare module 'react-virtuoso/dist/react-virtuoso.cjs.development.js' {
  declare module.exports: $Exports<'react-virtuoso/dist/react-virtuoso.cjs.development'>;
}
declare module 'react-virtuoso/dist/react-virtuoso.cjs.production.min.js' {
  declare module.exports: $Exports<'react-virtuoso/dist/react-virtuoso.cjs.production.min'>;
}
declare module 'react-virtuoso/dist/react-virtuoso.esm.js' {
  declare module.exports: $Exports<'react-virtuoso/dist/react-virtuoso.esm'>;
}
